In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model

In [2]:
df_multi = pd.read_csv("multiple_linear_regression_dataset.csv")

In [4]:
df_multi.head()

age  experience  income
0   25           1   30450
1   30           3   35670
2   47           2   31580
3   32           5   40130
4   43          10   47830

### Here age and experience are independent variables and income is dependent variable

In [5]:
df_multi.tail()

age  experience  income
15   41           6   38900
16   58          17   63600
17   23           1   30870
18   44           9   44190
19   37          10   48700

In [7]:
df_multi.shape

(20, 3)

In [8]:
df_multi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         20 non-null     int64
 1   experience  20 non-null     int64
 2   income      20 non-null     int64
dtypes: int64(3)
memory usage: 612.0 bytes


In [9]:
df_multi.describe()

age  experience        income
count  20.000000   20.000000     20.000000
mean   39.650000    6.200000  40735.500000
std    10.027725    4.124382   8439.797625
min    23.000000    1.000000  27840.000000
25%    31.500000    3.750000  35452.500000
50%    40.000000    5.000000  40190.000000
75%    47.000000    9.000000  45390.000000
max    58.000000   17.000000  63600.000000

In [10]:
df = df_multi.drop('income',axis='columns')
df

age  experience
0    25           1
1    30           3
2    47           2
3    32           5
4    43          10
5    51           7
6    28           5
7    33           4
8    37           5
9    39           8
10   29           1
11   47           9
12   54           5
13   51           4
14   44          12
15   41           6
16   58          17
17   23           1
18   44           9
19   37          10

In [15]:
df_dep = df_multi.iloc[:,2:] #depen

In [16]:
df_dep

income
0    30450
1    35670
2    31580
3    40130
4    47830
5    41630
6    41340
7    37650
8    40250
9    45150
10   27840
11   46110
12   36720
13   34800
14   51300
15   38900
16   63600
17   30870
18   44190
19   48700

In [17]:
import plotly.express as px
import plotly.graph_objects as go

In [20]:
fig = px.scatter_3d(df,x = df.age,y=df.experience,z = df_dep)
fig.show()

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [21]:
reg = linear_model.LinearRegression()
reg.fit(df,df_dep)

LinearRegression()

In [22]:
reg.coef_

array([[ -99.19535546, 2162.40419192]])

In [23]:
reg.intercept_

array([31261.6898541])

In [24]:
reg.predict([[43, 10]])

C:\Users\Pakistan\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[48620.33148852]])

In [25]:
# Y = m1 * X1 + m2 * X2 + b (m1,m2 are coefficient and b is intercept)
-99.19535546*43 + 2162.40419192*10 + 31261.6898541

48620.331488519994